swagger: '2.0'
info:
  title: costco order
  version: 0.0.1
  description: costco order
  x-ibm-name: costco order
paths:
  /init:
    get:
      description: costco order types app
      operationId: orders
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
        "405":
          description: "Invalid input"
        "404":
          description: "Not Found"
    post:
      description: costco order types app
      operationId: create
      consumes:
      - "application/text"
      produces:
      - "application/text"
      responses:
        "200":
          description: "Success"
  /listOrderTypes:
    get:
      operationId: listOrderTypes
      responses:
        '200':
          description: The operation was successful.
      consumes:
        - application/json
      produces:
        - application/json
      description: List Costco Orders
definitions:
  numbers:
    type: object
    properties:
      num1:
        type: integer
      num2:
        type: integer
schemes:
  - http
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
host: costco-orders-git-openshift.itzroks-663002b1mb-xbphnt-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
